import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import Navbar from "@/components/shared/Navbar";

export const metadata: Metadata = {
  title: "my-port-folio",
  description: "Generated by Shanto(Full Stack Developer)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Navbar></Navbar>
      <div className="min-h-screen">  {children}</div>
      </body>
    </html>
  );
}
